repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0  # Use the latest version of the ruff-pre-commit hook
    hooks:
      - id: ruff
        args: ["--fix", "--ignore", "E501"]  # Automatically fix issues and ignore line too long
